### ISSUE TITLE
How to fix the cache issue

### ISSUE THREAD

**Issue by Elizafox** [mbilokonsky/ambassador#1]
Hey,

So I'm not real familiar with JavaScript, but I'm a programmer in other languages, so I'm going to be general here. There's a simple way to fix your cache issue without using a cache at all.

Do this instead:
* Your first query should be the 30 days one. That's fine.
* In the toots reported from your query, select the newest one. You can do this pragmatically if you want. It doesn't matter.
* Store the timestamp in some persistent file for later usage in case of a shutdown. Read the file on startup if it's there.
* Use this query:

```sql
SELECT id 
FROM statuses 
WHERE favourites_count > (
  SELECT avg(favourites_count) 
  FROM statuses 
  WHERE favourites_count > 1
  AND created_at > (latest toot timestamp)
)
AND created_at > (latest toot timestamp);
```

It should be relatively efficient. I'm not sure how to make that SQL query better myself; I'm no SQL expert by any means.

**Comment by Elizafox** [comment]
Also, you're likely going to want an `ORDER BY` statement in your query. Probably `ORDER BY favourites_count DESC`. That way you post the toots from lowest to highest.

**Comment by mbilokonsky** [comment]
Hi, thanks for the feedback! 

So, this is working I think slightly differently than you're expecting. The ordering doesn't actually matter - the 30 day window is there in case some toot wasn't popular right away, but became popular enough within 30 days to reach the threshold. (I'm going to dramatically lower this number).

I think the better fix, then, is just to say `boosted = {}` once a day and let it build back up naturally. 

The bigger fix I want to make sure I add is visibility - I don't want to be boosting anything that wasn't public! ><
